names=['bob','alice','tom','jerry']
print(names[0])
print(names[1].title())
print(names[2].upper())
print(names[-1])
message=names[0]+",nice to meet u!"
print(message)
brands=("stusst","supreme","palace")
print("I would like to own a "+brands[1].title()+" pailide\n")

name_list=['dingding','lala','dixi','po']
invited=[name_list.pop(),name_list.pop()]
print(name_list)
print(invited)
print("I invite "+invited[0]+" and "+invited[1] +" to my party.")
print("but "+invited[0]+" can't come.")
name_list.append(invited.pop(0))
invited.append(name_list.pop(1))
print(name_list)
print(invited)
print("So I invite "+invited[0]+" and "+invited[1]+" come to my party.")
print("I find bigger restaurant.")
houbu=name_list.pop(0)
print(houbu)
invited.insert(0,houbu)
print(invited)
print("So I invite "+houbu+" to my party too.")
print("But the restuarant tell me that they have no extra table for me.")
name_list.append(invited.pop(0))
print(name_list)
print("sorry,"+name_list[-1]+".")
print(invited)
print("the num of invited people:"+str(len(invited)))
print("Let's go "+invited[0]+" and "+invited[1]+".")
del invited[0]
invited.remove('lala')
print(invited)
print("\n")

local=['xian','shanghai','tokyo','osaka','nagoya']
print(local)
print(sorted(local))
print(local)
print(sorted(local,reverse=True))
print(local)
local.reverse()
print(local)
local.reverse()
print(local)
local.sort()
print(local)
local.sort(reverse=True)
print(local)
print("\n")

Luxury=['gucci','ysl','lv','chanel','armani']
print(Luxury)
print(Luxury[0].title())
print(Luxury[-1].upper())
print("My friend like "+Luxury[2].upper()+".")
Luxury[3]='caoch'
print(Luxury)
Luxury.append('dior')
print(Luxury)
Luxury.insert(1,'hermes')
print(Luxury)
del Luxury[2]
print(Luxury)
buy=[Luxury.pop(-3)]
print(buy)
print(Luxury)
Luxury.remove('armani')
print(Luxury)
print(sorted(Luxury))
print(sorted(Luxury,reverse=True))
print(Luxury)
Luxury.sort()
print(Luxury)
Luxury.sort(reverse=True)
print(Luxury)
Luxury.reverse()
print(Luxury)
Luxury.reverse()
print(Luxury)
print("I like these "+str(len(Luxury))+" Luxury brands.")